### PR TITLE
Support binary maxmind db to reduce RAM

### PR DESCRIPTION
**Pull request by stephen-soltesz**
The first version of the uuid-annotator used upwards of ~2.5GB RSS as a result of expensive CSV load operations. At steady state, the Go process reported ~1GB of "in use" RAM. With four experiments currently using the uuid-annoator, this meant that ~6GB of RAM was claimed but unused, limiting the capacity of the rest of the system.

Using the binary Maxmind DB, we can reduce the RSS by 10x. The aggregate RAM usage of the uuid-annotator with the binary Maxmind DB should be safe to deploy to production. The image below illustrates the dramatic drop in RAM usage with this change.

uuid-rss2

This change also makes the `rawfile` package (formerly `zipfile`) agnostic about the underlying filetype, leaving the data readers to interpret the format and providing helper functions such as `ReadFileFromTar()`.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[main_test.go, line 32 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0QBZUV4FUVji4Kb4Sc:-M0QBZUV4FUVji4Kb4Sd:b-62vzwz) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/main_test.go#L32)):*
> ```Go
> 	go srv.Serve(mainCtx)
> 
> 	// Cancel main after a tenth of a second.
> ```

Update comment

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[main.go, line 33 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SjrtNAWDkZkOfJLZi:-M0SjrtNAWDkZkOfJLZj:b-mcl7h1) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/main.go#L33)):*
> ```
>  we don't actually re-download it if the data is new
> ```
... only download it if the data is new ???
___
*[rawfile/provider.go, line 23 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0Sl9lfCwqYT1BjrUnC:-M0Sl9lfCwqYT1BjrUnD:b-h76kng) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/rawfile/provider.go#L23)):*
> ```Go
> 
> // Provider is the interface implemented by everything that can return raw files.
> type Provider interface {
> ```

How about:
   Refresh() ReadCloser  // Returns a non-nil reader iff there is new data.

Or, if ReadCloser doesn't work, then []byte, but still nil if the data hasn't changed.
___
*[rawfile/provider.go, line 27 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SjJJmCxUfVXXSIXm2:-M0SjJJnCpze2ixvUoAh:bc67sf4) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/rawfile/provider.go#L27)):*
> ```Go
> 	// URL. It may be called multiple times. Caching is left up to the individual
> 	// Provider implementation.
> 	Get(ctx context.Context) ([]byte, error)
> ```

Could this return a generic Reader?  Or is byte slice the only common form?
___
*[rawfile/provider.go, line 35 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SkrjJDLg5crlR-zmf:-M0SkrjJDLg5crlR-zmg:bzaqrnp) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/rawfile/provider.go#L35)):*
> ```Go
> 	client           stiface.Client
> 	md5              []byte
> 	cachedReader     []byte
> ```

Is there actually any need to cache the data, or just the md5?  Seems like the data should only be read and used once.

**Review by stephen-soltesz — COMMENTED** [review]
I've updated the unit tests to use actual test data published by Maxmind, now described in the testdata/README.

I like your suggestions for improving the interface between provider & the annotator. Eliminating the 2nd copy was already on my short list of what to do next. Can this be completed in a future PR?

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-:-M0TxiEP47OvuUkV67bR:bapf01l)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[main.go, line 33 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SjrtNAWDkZkOfJLZi:-M0THmPl1RhB0AP5zLHJ:br4fggr) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/main.go#L33)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> ```
>  we don't actually re-download it if the data is new
> ```
... only download it if the data is new ???
</blockquote></details>

Looked like a typo. Fixed.
___
*[main_test.go, line 32 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0QBZUV4FUVji4Kb4Sc:-M0TvXrP8bvxT7VJG4ie:bq8sdkb) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/main_test.go#L32)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Update comment
</blockquote></details>

This change was a hack -- I've removed the hack. 
___
*[rawfile/provider.go, line 35 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SkrjJDLg5crlR-zmf:-M0Twvz40wQ4b-FiCv2e:bkiu6ps) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/rawfile/provider.go#L35)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is there actually any need to cache the data, or just the md5?  Seems like the data should only be read and used once.
</blockquote></details>

I agree. Can this architectural change be deferred to a future issue?

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[rawfile/provider.go, line 35 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SkrjJDLg5crlR-zmf:-M0U-onE1JL_0TVl8fqv:b-2sxpcp) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/rawfile/provider.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I agree. Can this architectural change be deferred to a future issue?
</blockquote></details>

Please add a TODO or issue.

**Review by gfr10598 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-:-M0U0qdd5s523s7F0BD_:bg7igkv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[rawfile/provider.go, line 35 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-M0SkrjJDLg5crlR-zmf:-M0UDeeiAuasEuJNntJS:b-zi4cx5) ([raw file](https://github.com/m-lab/uuid-annotator/blob/234993975dc2552ce19a010182d25467eec5452e/rawfile/provider.go#L35)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a TODO or issue.
</blockquote></details>

https://github.com/m-lab/uuid-annotator/issues/11

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/10#-:-M0UGb3D92UeBLYPO02H:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/534

**Pull request merged**
