### PR TITLE
Multiple ips

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/29)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/29)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[ipservice/client.go, line 31 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-M3DOnXQDjQ0L_jkd0kk:-M3DOnXQDjQ0L_jkd0kl:b-fifv3g) ([raw file](https://github.com/m-lab/uuid-annotator/blob/0d2f2ff39143b71ac6d120d7384998b391f5e1b7/ipservice/client.go#L31)):*
> ```Go
> 	// passed-in IP addresses. Invalid IPs will not be present in the returned
> 	// map.
> 	Annotate(ctx context.Context, ips []string) (map[string]*annotator.ClientAnnotations, error)
> ```

What is the planned archival format for the traceroute caller for the hop annotations? Will it require restructuring the map returned by `Annotate()`?
___
*[ipservice/client.go, line 50 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-M3DPPge64ZtPPpNS7gX:-M3DPPge64ZtPPpNS7gY:b-km9a93) ([raw file](https://github.com/m-lab/uuid-annotator/blob/0d2f2ff39143b71ac6d120d7384998b391f5e1b7/ipservice/client.go#L50)):*
> ```Go
> 		ipstrings = append(ipstrings, "ip="+url.QueryEscape(ip))
> 	}
> 	u := "http://unix/v1/annotate/ips?" + strings.Join(ipstrings, ",")
> ```

I expected to see `&` as the parameter separator. Is comma `,` also valid? Rather than manually constructing the URL and query parameters, please consider using `url.URL` and `url.Values` with `url.Values.Encode`. This would eliminate any special knowledge the code needs about HTTP URLs or query parameter structure.

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/29)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[ipservice/client.go, line 31 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-M3DOnXQDjQ0L_jkd0kk:-M3HGTGB5Igm5Jtp43f-:b-tbgo1r) ([raw file](https://github.com/m-lab/uuid-annotator/blob/0d2f2ff39143b71ac6d120d7384998b391f5e1b7/ipservice/client.go#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the planned archival format for the traceroute caller for the hop annotations? Will it require restructuring the map returned by `Annotate()`?
</blockquote></details>

I hope not? However, I think that having the uuid-annotator spit data out in the same format along all its output channels is the correct thing to do.
___
*[ipservice/client.go, line 50 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-M3DPPge64ZtPPpNS7gX:-M3HGDor9LLZvHlswSrz:b-lo20a3) ([raw file](https://github.com/m-lab/uuid-annotator/blob/0d2f2ff39143b71ac6d120d7384998b391f5e1b7/ipservice/client.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I expected to see `&` as the parameter separator. Is comma `,` also valid? Rather than manually constructing the URL and query parameters, please consider using `url.URL` and `url.Values` with `url.Values.Encode`. This would eliminate any special knowledge the code needs about HTTP URLs or query parameter structure.
</blockquote></details>

Now using URL libraries, and actually testing the "multiple IP" case.  Which did not work, but because it was untested the unit tests all passed. Now it is tested and passes.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-:-M3HIucP0PHoq9uYfKx-:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe)

___
*[ipservice/client.go, line 50 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-M3DPPge64ZtPPpNS7gX:-M3HIDdgCgwrRlNj_JrV:b-kbcgdo) ([raw file](https://github.com/m-lab/uuid-annotator/blob/0d2f2ff39143b71ac6d120d7384998b391f5e1b7/ipservice/client.go#L50)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Now using URL libraries, and actually testing the "multiple IP" case.  Which did not work, but because it was untested the unit tests all passed. Now it is tested and passes.
</blockquote></details>

I wouldn't be mad about:

```
u := url.URL{
    Scheme: "http",
    Host: "unix",
    Path: "/v1/annotate/ips",
    RawQuery: ipvalues.Encode(),
}
resp, err := c.httpc.Get(u.String())
```

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/29)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[ipservice/client.go, line 50 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/29#-M3DPPge64ZtPPpNS7gX:-M3HJe1TDq380dAUSGiS:bc77y7f) ([raw file](https://github.com/m-lab/uuid-annotator/blob/0d2f2ff39143b71ac6d120d7384998b391f5e1b7/ipservice/client.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I wouldn't be mad about:

```
u := url.URL{
    Scheme: "http",
    Host: "unix",
    Path: "/v1/annotate/ips",
    RawQuery: ipvalues.Encode(),
}
resp, err := c.httpc.Get(u.String())
```
</blockquote></details>

Changed to prevent anger. ;)

**Pull request merged**
