### PR TITLE
Add ASN annotation to uuid-annotator

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds ASN annotations to the uuid-annotator based on route views.

This change includes two new flags for specifying the IPv4 and IPv6 routeview data. And, this change uses the flagx.URL flag type for all URL flags.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13)

### CODE REVIEW

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz and @yachang)

___
*[asnannotator/routeview.go, line 72 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0ZG4Em1FhtURewEMNb:-M0ZG4Em1FhtURewEMNc:b-kpm7uf) ([raw file](https://github.com/m-lab/uuid-annotator/blob/7fd546448727843bba739797c051abc8d6bfebd5/asnannotator/routeview.go#L72)):*
> ```Go
> 	for _, local := range a.localIPs {
> 		if ID.SrcIP == local.String() {
> 			dir = s2c
> ```

break here?
___
*[asnannotator/routeview.go, line 75 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0ZG6ghAA-SPtR_1d4t:-M0ZG6ghAA-SPtR_1d4u:b-kpm7uf) ([raw file](https://github.com/m-lab/uuid-annotator/blob/7fd546448727843bba739797c051abc8d6bfebd5/asnannotator/routeview.go#L75)):*
> ```Go
> 		}
> 		if ID.DstIP == local.String() {
> 			dir = c2s
> ```

break here?

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz and @yachang)

___
*[asnannotator/routeview.go, line 83 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0ZGMcc1GBG-lQDt3vR:-M0ZGMcc1GBG-lQDt3vS:b-2qks3g) ([raw file](https://github.com/m-lab/uuid-annotator/blob/7fd546448727843bba739797c051abc8d6bfebd5/asnannotator/routeview.go#L83)):*
> ```Go
> 	case s2c:
> 		src = &annotations.Server
> 		dst = &annotations.Client
> ```

Those code can be merged into above for loop

**Review by stephen-soltesz — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-:-M0Zanks-4DJFwb4ACTR:b-833305)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[asnannotator/routeview.go, line 72 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0ZG4Em1FhtURewEMNb:-M0ZZYR0C1bybp3451Ef:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/7fd546448727843bba739797c051abc8d6bfebd5/asnannotator/routeview.go#L72)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

break here?
</blockquote></details>

Done.
___
*[asnannotator/routeview.go, line 75 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0ZG6ghAA-SPtR_1d4t:-M0ZZ_-R10xznDkCOrA9:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/7fd546448727843bba739797c051abc8d6bfebd5/asnannotator/routeview.go#L75)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

break here?
</blockquote></details>

Done.
___
*[asnannotator/routeview.go, line 83 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0ZGMcc1GBG-lQDt3vR:-M0ZQAch3D-4i8hBe2ZV:b-mq3s3v) ([raw file](https://github.com/m-lab/uuid-annotator/blob/7fd546448727843bba739797c051abc8d6bfebd5/asnannotator/routeview.go#L83)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Those code can be merged into above for loop 
</blockquote></details>

I was trying to follow the same pattern as the ipannotator -- https://github.com/m-lab/uuid-annotator/blob/master/ipannotator/ipannotator.go#L50

But, it may not make sense to do that twice, so I've moved the direction logic to the annotator package and call it here instead.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/534

**Review by yachang — CHANGES_REQUESTED** [review]
Only minor comments.

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-:-M0c9wu09QzTcmELho1p:b7rfpkw)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz and @yachang)

___
*[asnannotator/routeview_test.go, line 78 at r4](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0c9hk_0coFE9HDfJk2:-M0c9hkaEakbICg9vNLb:bo38i05) ([raw file](https://github.com/m-lab/uuid-annotator/blob/545f9f8ca14dcbc1eb5daf51c5f772696a51f741/asnannotator/routeview_test.go#L78)):*
> ```
> wantErr
> ```
miss "wantErr" as false here?
___
*[asnannotator/routeview_test.go, line 105 at r4](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0c9mUI3HUqy1cMUo5H:-M0c9mUI3HUqy1cMUo5I:bt5xfio) ([raw file](https://github.com/m-lab/uuid-annotator/blob/545f9f8ca14dcbc1eb5daf51c5f772696a51f741/asnannotator/routeview_test.go#L105)):*
> ```Go
> 					},
> 				},
> 			},
> ```

miss "wantErr"

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-:-M0cA0FM2dA_PfseO48d:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz and @yachang)

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/13)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

___
*[asnannotator/routeview_test.go, line 78 at r4](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0c9hk_0coFE9HDfJk2:-M0cS9PkAIv23g3ziXb4:b-2rkdsz) ([raw file](https://github.com/m-lab/uuid-annotator/blob/545f9f8ca14dcbc1eb5daf51c5f772696a51f741/asnannotator/routeview_test.go#L78)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

> ```
> wantErr
> ```
miss "wantErr" as false here?
</blockquote></details>

By convention, it's generally okay to leave fields absent if we want them to have their default value. In Go, the default value of a bool is false. So, because these are labeled as "success*" cases, I think it's appropriate to leave `wantErr: false` out.
___
*[asnannotator/routeview_test.go, line 105 at r4](https://reviewable.io/reviews/m-lab/uuid-annotator/13#-M0c9mUI3HUqy1cMUo5H:-M0cSPv1EnJMG1VSY7RO:bi1q2rc) ([raw file](https://github.com/m-lab/uuid-annotator/blob/545f9f8ca14dcbc1eb5daf51c5f772696a51f741/asnannotator/routeview_test.go#L105)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

miss "wantErr"
</blockquote></details>

Same reason as above.

**Pull request merged**
