### PR TITLE
Add RouteView parser and enable ASN annotations

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a routeview package for parsing and searching the RV data. This will be used by the ASN annotator.

`Search` uses golang `sort.Search`. `ParseRouteView` is designed to reduce memory requirements as much as possible. This is accomplished in two ways:

* Smaller netblocks are merged with larger netblocks when Contains() is true and ASNs match. (saves ~40MB)
* Because many ASNs are duplicates, IPNet instances reference string pointers. (saves ~4MB).

This was the best of four approaches as benchmarked from sandbox-soltesz-scratch, including:

* annotation-service/asn.LoadASNDatasetFromReader
* ParseRouteView without netblock coalescing 
* ParseRouteView with early Systems parsing

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/18)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/18)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[routeview/parse.go, line 15 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xKiNO86V1nrNbpQ7G:-M0xKiNP5quxHtv70Qc8:bsh4py4) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L15)):*
> ```Go
> 
> 	"github.com/m-lab/uuid-annotator/annotator"
> 	"github.com/xorcare/pointer"
> ```

Please separate m-lab imports and non-m-lab imports.
What is the motivation for using xorcare/pointer?
___
*[routeview/parse.go, line 21 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xNTYK-98NH2w2AK4r:-M0xNTYK-98NH2w2AK4s:b-2f0oua) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L21)):*
> ```Go
> type IPNet struct {
> 	net.IPNet
> 	Systems *string
> ```

I'm not convinced the indirection is worthwhile.   4MB doesn't seem like a signficant amount, and it adds a dereferenced.
___
*[routeview/parse.go, line 28 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xMzRy0mgNPP4GVEQY:-M0xMzRy0mgNPP4GVEQZ:b-7atltu) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L28)):*
> ```Go
> 
> type Index struct {
> 	n IPNetSlice
> ```

"n" doesn't make it easy to understand.
Does putting this in a struct add any value?  Or could you just rename IPNetSlice to Index?
___
*[routeview/parse.go, line 93 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xM82l90WOYhaj4__L:-M0xM82l90WOYhaj4__M:b-pdxky6) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L93)):*
> ```Go
> 		if _, ok := sm[record[2]]; !ok {
> 			// break string connection to underlying csv reader ram.
> 			sm[record[2]] = pointer.String(string([]byte(record[2])))
> ```

Can you just use golang copy for this?
___
*[routeview/parse.go, line 96 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xMcg79U1BIZecH20n:-M0xMcg79U1BIZecH20o:bb7phvt) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L96)):*
> ```Go
> 		}
> 		if len(result) > 1 && result[len(result)-1].Contains(n.IP) && *(result[len(result)-1].Systems) == record[2] {
> 			// If the last thing contains the current one witht he same systems, skip it.
> ```

typo
___
*[routeview/parse.go, line 113 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xO4Va87fCiwKtMXgR:-M0xO4Va87fCiwKtMXgS:b-y4eaho) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L113)):*
> ```Go
> 
> // Search attempts to find the given src IP in n.
> func (rv *Index) Search(src string) (IPNet, error) {
> ```

s/src/IP/ 
___
*[routeview/parse.go, line 119 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xOd3_AJ7rkctBUrUP:-M0xOd3_AJ7rkctBUrUQ:b-rz346j) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L119)):*
> ```Go
> 		ip = ip.To4()
> 	}
> 	x := sort.Search(len(rv.n), func(i int) bool {
> ```

s/x/node/

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/18)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[routeview/parse.go, line 15 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xKiNO86V1nrNbpQ7G:-M0xcSZcE67Y4b6tFExI:b-bjz2m7) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L15)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please separate m-lab imports and non-m-lab imports.
What is the motivation for using xorcare/pointer?
</blockquote></details>

I've been noticing/thinking about how we should be organizing our imports. We haven't done it consistently -- something like: system, third-party, m-lab/*?

Regarding pointer -- I just wanted an easy way to copy a string & get it's pointer. The reason I wanted to do that is because in the memory profiling I was doing recently to decide on the most efficient RAM usage, _without_ the copy, I was seeing all the memory allocated by the CSV reader remain in the "inuse" stats. With the copy, that memory could be freed. I've understood this as a combination of a) string slices referencing parts of larger pieces of memory, and b) some reluctance that Go has for consolidating unreferenced parts of arrays where any part is referenced by a slice. The copy allows the bytes to be "released" from the larger underlying array.
___
*[routeview/parse.go, line 21 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xNTYK-98NH2w2AK4r:-M0xfualCOYGUsews83e:b-qz104w) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L21)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'm not convinced the indirection is worthwhile.   4MB doesn't seem like a signficant amount, and it adds a dereferenced.
</blockquote></details>

I was on a roll. It adds up. Removed.
___
*[routeview/parse.go, line 28 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xMzRy0mgNPP4GVEQY:-M0xdYSmDbSqe3gfhBto:b-chsn6k) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

"n" doesn't make it easy to understand.
Does putting this in a struct add any value?  Or could you just rename IPNetSlice to Index?
</blockquote></details>

Removed in favor of just using the IPNetSlice.
___
*[routeview/parse.go, line 93 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xM82l90WOYhaj4__L:-M0xdeFq5N0D9JefzhHl:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L93)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can you just use golang copy for this?
</blockquote></details>

Done.
___
*[routeview/parse.go, line 96 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xMcg79U1BIZecH20n:-M0xdgmk623e4hwUvSqS:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L96)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[routeview/parse.go, line 113 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xO4Va87fCiwKtMXgR:-M0xeJmN6OLdFPW-0DvZ:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L113)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/src/IP/ 
</blockquote></details>

Done.
___
*[routeview/parse.go, line 119 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xOd3_AJ7rkctBUrUP:-M0xeKmdCc6R9p4n9fK2:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L119)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/x/node/
</blockquote></details>

Done.

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-:-M0xqtTm5cLO_mzovarO:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[routeview/parse.go, line 15 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xKiNO86V1nrNbpQ7G:-M0xqFzj93YDbmlmCDm_:b-aqit3d) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I've been noticing/thinking about how we should be organizing our imports. We haven't done it consistently -- something like: system, third-party, m-lab/*?

Regarding pointer -- I just wanted an easy way to copy a string & get it's pointer. The reason I wanted to do that is because in the memory profiling I was doing recently to decide on the most efficient RAM usage, _without_ the copy, I was seeing all the memory allocated by the CSV reader remain in the "inuse" stats. With the copy, that memory could be freed. I've understood this as a combination of a) string slices referencing parts of larger pieces of memory, and b) some reluctance that Go has for consolidating unreferenced parts of arrays where any part is referenced by a slice. The copy allows the bytes to be "released" from the larger underlying array.
</blockquote></details>

Definitely good thing to do.  I'm just hoping to avoid using a third party library if it can be done simply with standard go libraries.
___
*[routeview/parse.go, line 93 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xM82l90WOYhaj4__L:-M0xmDVT5fIA7vEd48Y4:bf0ze25) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L93)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI, Looks like strings.Repeat(record[2], 1) does a single allocation instead of two.

	rCpy := strings.Repeat(record[2], 1)
	sm[rCpy] = string(rCpy)

Alternatively, it looks like strings.Build also does just a single allocation:
	b := strings.Builder{}
	b.WriteString(x)
	rCpy := b.String()
	sm[rCpy] = string(rCpy)
___
*[routeview/parse.go, line 113 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xO4Va87fCiwKtMXgR:-M0xqhu42rpvPUG-Pjmx:b3lz2y8) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Or ip, I guess.  Up to you.
___
*[routeview/parse.go, line 91 at r3](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xhtSH7fsE86DS22xV:-M0xhtSI8oOAwCiAXNte:bcgs9y8) ([raw file](https://github.com/m-lab/uuid-annotator/blob/b4eb472168ca2fab706ba40321d37d7cb6fbc1cc/routeview/parse.go#L91)):*
> ```Go
> 			dst := make([]byte, len(record[2]))
> 			copy(dst, []byte(record[2]))
> 			sm[record[2]] = string(dst)
> ```

I think this is doing two copies...

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/18)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[routeview/parse.go, line 113 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xO4Va87fCiwKtMXgR:-M0yC7nG2XDQW1qh13i_:b-oqgmgf) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c8c8e5be9610c0a2ed648d7d1f8ed768c1252454/routeview/parse.go#L113)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Or ip, I guess.  Up to you.
</blockquote></details>

I think `ip` is the right name inside the function body; I couldn't think of a good second name for the parameter. All the `net` package `Parse*` functions name the parameter `s`. I tried that. Trying that -- still doesn't feel quite right. Still open to suggestions!
___
*[routeview/parse.go, line 91 at r3](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xhtSH7fsE86DS22xV:-M0yBfiFD5lvascI8I1u:b-h954qc) ([raw file](https://github.com/m-lab/uuid-annotator/blob/b4eb472168ca2fab706ba40321d37d7cb6fbc1cc/routeview/parse.go#L91)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this is doing two copies...
</blockquote></details>

Does a cast imply a copy? I thought it did not. What are the two copies you see?

Using `strings.Repeat()` now.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/18)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[routeview/parse.go, line 91 at r3](https://reviewable.io/reviews/m-lab/uuid-annotator/18#-M0xhtSH7fsE86DS22xV:-M0y_Na05iquqysNqQzm:bf6dauu) ([raw file](https://github.com/m-lab/uuid-annotator/blob/b4eb472168ca2fab706ba40321d37d7cb6fbc1cc/routeview/parse.go#L91)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does a cast imply a copy? I thought it did not. What are the two copies you see?

Using `strings.Repeat()` now.
</blockquote></details>

Cast from string to byte slice does a copy, and vice-versa, because string is immutable, and slice is not.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/534

**Pull request merged**
