### PR TITLE
Read IP metadata from GCS

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/4)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/4)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[zipfile/provider.go, line 12 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_HS1X44rKoe9whqw7:-Ly_HS1Y-xNIrZvBjf7_:b-m3m8ax) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider.go#L12)):*
> ```Go
> 	"net/url"
> 
> 	"github.com/GoogleCloudPlatform/google-cloud-go-testing/storage/stiface"
> ```

Please use the canonical path for this package throughout.

`github.com/googleapis/google-cloud-go-testing/...`

I don't know how to discover that other than go.mod telling me.

I believe it's preferable in general to use the canonical URL b/c the import path defines the full type name and, for example, I've gotten into trouble with `iterator.Done` from two different packages, the one returned vs the one imported.
___
*[zipfile/provider.go, line 58 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_EBN4BA2FWKjPyEBU:-Ly_EBN56ax4oxRexlNI:be3an44) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider.go#L58)):*
> ```Go
> 		}
> 		g.cachedReader, err = zip.NewReader(bytes.NewReader(data), int64(len(data)))
> 		g.md5 = oa.MD5
> ```

Only update md5 if `err == nil`?

Also, maybe sanity check the oa.MD5 value and warn if it's out of the ordinary.
___
*[zipfile/provider.go, line 58 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_Jo511XjiBtXESLPe:-Ly_Jo511XjiBtXESLPf:b-iwulhf) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider.go#L58)):*
> ```Go
> 		}
> 		g.cachedReader, err = zip.NewReader(bytes.NewReader(data), int64(len(data)))
> 		g.md5 = oa.MD5
> ```

Is it still planned to export this value for prometheus so we can compare it to the "latest" reported by the downloader?
___
*[zipfile/provider_test.go, line 166 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_LT1p-l6wSeM3SAi8:-Ly_LT1qB3FEz9p5KsNM:b-89x5wz) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider_test.go#L166)):*
> ```Go
> 		name    string
> 		fields  fields
> 		args    args
> ```

ctx is not specified in the test setup. I suggest removing this field here and using a static background ctx in the test run. This borders on a nit. The motivation is to reduce unnecessary fields from the tests.
___
*[zipfile/provider_test.go, line 249 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_KkaJ0IQOTEdh9a_q:-Ly_KkaK-wHToQ2JNfxM:b6sro01) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider_test.go#L249)):*
> ```Go
> 				},
> 			},
> 			want: &zip.Reader{}, // non-nil want
> ```

Can this be `readerForZipfileOnDisk` and replace the `== nil ` checks with `tt.want != got`?

Otherwise, perhaps change `want` to a bool? The combination of `want` without actually caring about the value is unexpected, and it leads to this use of an empty value to set a boolean state. But, actually checking value equality would be a little better, I think.

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/4)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[zipfile/provider.go, line 12 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_HS1X44rKoe9whqw7:-Ly_pPyEEQ4Zk5RytTkX:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider.go#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use the canonical path for this package throughout.

`github.com/googleapis/google-cloud-go-testing/...`

I don't know how to discover that other than go.mod telling me.

I believe it's preferable in general to use the canonical URL b/c the import path defines the full type name and, for example, I've gotten into trouble with `iterator.Done` from two different packages, the one returned vs the one imported.
</blockquote></details>

Done.
___
*[zipfile/provider.go, line 58 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_EBN4BA2FWKjPyEBU:-Ly_pQHx18NGlZcRje8O:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider.go#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Only update md5 if `err == nil`?

Also, maybe sanity check the oa.MD5 value and warn if it's out of the ordinary.
</blockquote></details>

Done.
___
*[zipfile/provider.go, line 58 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_Jo511XjiBtXESLPe:-Ly_r1BR0XNv0JRwe46w:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider.go#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it still planned to export this value for prometheus so we can compare it to the "latest" reported by the downloader?
</blockquote></details>

Done.
___
*[zipfile/provider_test.go, line 166 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_LT1p-l6wSeM3SAi8:-Ly_pQvEBB2eek5VctvI:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider_test.go#L166)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

ctx is not specified in the test setup. I suggest removing this field here and using a static background ctx in the test run. This borders on a nit. The motivation is to reduce unnecessary fields from the tests.
</blockquote></details>

Done.
___
*[zipfile/provider_test.go, line 249 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-Ly_KkaJ0IQOTEdh9a_q:-Ly_pRai78DtPl7q7Jyx:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/a7e675b1948367942a57b1467bfe3b2fa68e1b6a/zipfile/provider_test.go#L249)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can this be `readerForZipfileOnDisk` and replace the `== nil ` checks with `tt.want != got`?

Otherwise, perhaps change `want` to a bool? The combination of `want` without actually caring about the value is unexpected, and it leads to this use of an empty value to set a boolean state. But, actually checking value equality would be a little better, I think.
</blockquote></details>

Done.

**Comment by pboothe** [comment]
PTAL

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/4#-:-Ly_t3VW0kbXMRYuwlsw:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by pboothe** [comment]
https://github.com/m-lab/dev-tracker/issues/534

**Pull request merged**
