### PR TITLE
Adds IP decoration and a main method

### PR DESCRIPTION
**Pull request by pboothe**
Adds a `main()` and annotation from MaxMind zipfiles.

GCS functionality is still missing, but this PR is big enough without that.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/2)

### CODE REVIEW

**Comment by pboothe** [comment]
I honestly don't understand why coveralls still thinks coverage is at 100%. It's not. `ipannotator` and `main` are 100% covered. `annotator` contains no code, only structs and interfaces, and `zipfile` is untested and its most important method returns `errors.New("unimplemented")`

**Review by stephen-soltesz — APPROVED** [review]
goveralls (maybe go test coverprofile) does not include packages without unit tests in the counts.

:lgtm: -- just a few questions and nits. Looks really nice.

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-:-Ly6Ny4M2t4RdA-p2nLW:b-o46ok6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[Dockerfile, line 9 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6DrQ3ApDCPygnLjqZ:-Ly6DrQ3ApDCPygnLjq_:bdk7ku9) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/Dockerfile#L9)):*
> ```Dockerfile
>       -ldflags "-X github.com/m-lab/go/prometheusx.GitShortCommit=$(git log -1 --format=%h)" \
>       .
> RUN chmod a+rx /go/bin/uuid-annotator
> ```

Why is this needed?
___
*[main.go, line 30 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6G6Qi7NSzxFpw_TAA:-Ly6G6Qi7NSzxFpw_TAB:b57epgf) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/main.go#L30)):*
> ```Go
> 	eventbuffersize = flag.Int("eventbuffersize", 1000, "How many events should we buffer before dropping them?")
> 	reloadMin       = flag.Duration("reloadmin", time.Hour, "Minimum time to wait between reloads of backing data")
> 	reloadTime      = flag.Duration("reloadtime", 5*time.Hour, "Expected time to wait between reloads of backing data")
> ```

Does the current downloader try so frequently? I imagined once per day on average.. I guess the async update could result in some nodes annotating clients with one version of the mmdb and other nodes with a different version... I'm not sure what's best here.
___
*[main_test.go, line 43 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6Il-99h8_WRtU-iTr:-Ly6Il-A68Dgqlf-MwfI:b-uoq0ev) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/main_test.go#L43)):*
> ```Go
> 	}()
> 
> 	// Run main. Full coverage and no crash == success!
> ```

"... and return == success!"

most tests will eventually timeout and fail.
___
*[ipannotator/ipannotator.go, line 38 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6K0O71T24bPMrciwH:-Ly6K0O71T24bPMrciwI:b-723ysa) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/ipannotator/ipannotator.go#L38)):*
> ```Go
> 
> const (
> 	s2c direction = iota
> ```

Please make iota `unknown`.

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[Dockerfile, line 9 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6DrQ3ApDCPygnLjqZ:-LyA-meFC_JWYttCHN7x:b7hwiac) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/Dockerfile#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

It's not, it was just in the Dockerfile I copy and pasted and sed-ed from. Good catch.
___
*[main.go, line 30 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6G6Qi7NSzxFpw_TAA:-LyA-vtZAe5cRlTD_Fyn:bvidfke) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/main.go#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the current downloader try so frequently? I imagined once per day on average.. I guess the async update could result in some nodes annotating clients with one version of the mmdb and other nodes with a different version... I'm not sure what's best here.
</blockquote></details>

I think trying frequently is fine as long as (a) download failure is non-fatal for reloads and (b) caching actually works so that we don't actually re-download it if the data is new. Updated comment.
___
*[main_test.go, line 43 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6Il-99h8_WRtU-iTr:-LyA0kBB0RKg-KkhjQxE:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/main_test.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"... and return == success!"

most tests will eventually timeout and fail.
</blockquote></details>

Done.
___
*[ipannotator/ipannotator.go, line 38 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/2#-Ly6K0O71T24bPMrciwH:-LyA0qmb-Zmt1qJwzDUT:b-oz8tym) ([raw file](https://github.com/m-lab/uuid-annotator/blob/731186fc942c7a2ae4344f32f8d4d897c76faddc/ipannotator/ipannotator.go#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please make iota `unknown`.
</blockquote></details>

Good call.

**Comment by pboothe** [comment]
https://github.com/m-lab/dev-tracker/issues/534

**Pull request merged**
