### PR TITLE
Upgrade repo to Go 1.18

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/47)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/47)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/47#-N9bVJEK5OTF4GNd7loU:-N9bVJEL7TC5zOCM-a8N:bp1agdd) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c1f9914e71a3ccce145300d8c03a2ebcaadfbd81/Dockerfile#L5)):*
> ```Dockerfile
> COPY . /go/src/github.com/m-lab/uuid-annotator
> WORKDIR /go/src/github.com/m-lab/uuid-annotator
> RUN go get -v . && \
> ```

You mentioned wanting to use `CGO_ENABLED=0` here also. I think that too will be necessary for the different build & final environments.

**Comment by SaiedKazemi** [comment]
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/47#-N9bVJEK5OTF4GNd7loU:-N9bWRbT-ojlVAFdkBaj:bph98bn) ([raw file](https://github.com/m-lab/uuid-annotator/blob/c1f9914e71a3ccce145300d8c03a2ebcaadfbd81/Dockerfile#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You mentioned wanting to use `CGO_ENABLED=0` here also. I think that too will be necessary for the different build & final environments.
</blockquote></details>

Yes, based on our conversation and consistent with best practices, I will explicitly set `CGO_ENABLED=0` here and in other repos I will upgrade to Go 1.18.

**Comment by SaiedKazemi** [comment]
Will send follow up.

**Review by cristinaleonr — COMMENTED** [review]
Did you run `go mod tidy`? 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/47#-:-N9hP9Cd-6tDFPxdKwvq:bfpfxut)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Comment by SaiedKazemi** [comment]
I just committed an updated `go.sum` file.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/47#-:-N9hY4zp4YClY6RH3OWV:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Pull request merged**
