### PR TITLE
Changes to serverAnnotator to support project-decorated/flat hostnames.

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/25)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-:-M2pDnJh2tX0_9HgpxNQ:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[siteannotator/server.go, line 116 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-M2pDQL2907rG7_DGfvo:-M2pDQL2907rG7_DGfvp:bxfcex2) ([raw file](https://github.com/m-lab/uuid-annotator/blob/5c5bfe16bd9db8568db1ca8af803ae40a422b3a1/siteannotator/server.go#L116)):*
> ```Go
> 		return nil, err
> 	}
> 	re := regexp.MustCompile(`^(mlab\d)[.-]([a-z]{3}\d[\dtc])`)
> ```

It might be helpful to have a package in m-lab/go that defines expressions like this. I recall you added one to pusher recently. A single place could be better than N -- especially if we want to update it again to remove the "." after the migration or add a new node type for staging for example... or, thinking out loud, I wonder if the `t` suffix becomes redundant now with the project decoration convention now..

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/25)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[siteannotator/server.go, line 116 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-M2pDQL2907rG7_DGfvo:-M2tDMwz8FpFFoxWORgs:b-kwrbdz) ([raw file](https://github.com/m-lab/uuid-annotator/blob/5c5bfe16bd9db8568db1ca8af803ae40a422b3a1/siteannotator/server.go#L116)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It might be helpful to have a package in m-lab/go that defines expressions like this. I recall you added one to pusher recently. A single place could be better than N -- especially if we want to update it again to remove the "." after the migration or add a new node type for staging for example... or, thinking out loud, I wonder if the `t` suffix becomes redundant now with the project decoration convention now..
</blockquote></details>

https://github.com/m-lab/go/pull/107

I'm going to hold off merging this PR until the above review is done, and maybe we can use that here and also in pusher and perhaps other places.

As far as testing sites, I was also thinking about this lately, since we can not arbitrarily make any node a testing node. There doesn't seem to be much reason to maintain the `t` convention any longer.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - with one change.

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-:-M2tbqRQ7kYff0iSdTZK:bf7mrho)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[siteannotator/server.go, line 116 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-M2pDQL2907rG7_DGfvo:-M2tbW4v8wF57wF0aw3A:bndjwlr) ([raw file](https://github.com/m-lab/uuid-annotator/blob/5c5bfe16bd9db8568db1ca8af803ae40a422b3a1/siteannotator/server.go#L116)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

https://github.com/m-lab/go/pull/107

I'm going to hold off merging this PR until the above review is done, and maybe we can use that here and also in pusher and perhaps other places.

As far as testing sites, I was also thinking about this lately, since we can not arbitrarily make any node a testing node. There doesn't seem to be much reason to maintain the `t` convention any longer.
</blockquote></details>

Much simpler!
___
*[siteannotator/server.go, line 113 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-M2tb_UV9uDBf9ZlivaL:-M2tb_UV9uDBf9ZlivaM:b6hhadz) ([raw file](https://github.com/m-lab/uuid-annotator/blob/371f4131b4a072116374a97168cfcd5799ee340d/siteannotator/server.go#L113)):*
> ```Go
> 		return nil, err
> 	}
> 	host, err := host.Parse(g.hostname)
> ```

Please dont use the same name for variables as package names.

In this case, I might use `h` or `fields` for the variable.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/25)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[siteannotator/server.go, line 113 at r2](https://reviewable.io/reviews/m-lab/uuid-annotator/25#-M2tb_UV9uDBf9ZlivaL:-M2twzWdDhzWuOjIwvYb:b-896fix) ([raw file](https://github.com/m-lab/uuid-annotator/blob/371f4131b4a072116374a97168cfcd5799ee340d/siteannotator/server.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please dont use the same name for variables as package names.

In this case, I might use `h` or `fields` for the variable.
</blockquote></details>

Done.

**Pull request merged**
