### PR TITLE
Robustness to existing socket files

### LINKED ISSUE #34: Data race and socket binding
There's a data race in `main()` where it is possible for the annotation socket to be created and then for everything else to crash. Subsequent runs will find that the annotation socket already exists and be unable to make it.

We should either fix the race or make the daemon delete the specified socket filename if it already exists.

### PR DESCRIPTION
**Pull request by pboothe**
Also go vet cleanup and gofmt cleanup

Fixes #34

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/35)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/35)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[ipservice/server.go, line 118 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/35#-M66nXKQ7SiNgquNnWqV:-M66nXKQ7SiNgquNnWqW:b-89mqlr) ([raw file](https://github.com/m-lab/uuid-annotator/blob/1e2a04a37afbc4cbef3a11edd16133d977ed846b/ipservice/server.go#L118)):*
> ```Go
> 	// mean that prior start attempts have left an old bad socket file in the
> 	// way.
> 	os.Remove(sockfilename)
> ```

What happens to clients that are listening on the stale socket?

Could we instead guarantee in main.go that the connection to tcpinfo succeeds before creating the uuid server? 
https://github.com/m-lab/uuid-annotator/blob/master/main.go#L134-L143 -- 

Our pod containers have a specific dependency order:
* tcpinfo
* uuid-annotator
* traceroute-caller

It's possible to uuid-annotator to start first, create the NewServer socket but fail to connect to tcpinfo.

It's not clear to me that removing the socket unconditionally is preferable b/c it may complicate handling for traceroute-caller.

Why is this preferable to ensuring that uuid-annotator's dependencies are met before creating this socket?

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/35)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[ipservice/server.go, line 118 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/35#-M66nXKQ7SiNgquNnWqV:-M6V4r8V-oriH38w6ry6:b-8gq63q) ([raw file](https://github.com/m-lab/uuid-annotator/blob/1e2a04a37afbc4cbef3a11edd16133d977ed846b/ipservice/server.go#L118)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What happens to clients that are listening on the stale socket?

Could we instead guarantee in main.go that the connection to tcpinfo succeeds before creating the uuid server? 
https://github.com/m-lab/uuid-annotator/blob/master/main.go#L134-L143 -- 

Our pod containers have a specific dependency order:
* tcpinfo
* uuid-annotator
* traceroute-caller

It's possible to uuid-annotator to start first, create the NewServer socket but fail to connect to tcpinfo.

It's not clear to me that removing the socket unconditionally is preferable b/c it may complicate handling for traceroute-caller.

Why is this preferable to ensuring that uuid-annotator's dependencies are met before creating this socket?
</blockquote></details>

This new behavior is necessary, if we are to assume that a spurious transient crash in tcp-info or uuid-annotator ever could exist. I understand your comment to be worrying that this new behavior might not be sufficient.

No clients can be listening on the stale socket, as the server closing causes them to be disconnected. I don't know why Linux doesn't automatically reap socket filenames when the server-side closes, but if the OS won't reap the name,  then we should do what it turns out every other unix-domain-socket service does, and unlink the file right before we bind it. bind of a unix domain socket fails if the filename exists, even if the filename is owned by the current user. unix domain sockets, it turns out, can't be re-used. bind() must be given a filename that does not exist.

Client connections close as soon as the server-side closes, and new connections don't return success unless there is a server listening on the other end.  Crashing (due to a bug or an assertion failure on startup)  and then unlink&bind when the new instance starts is a safe behavior. I can add unit tests of these assertions about the surrounding OS if you would like.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/35#-:-M6VmRb30FeJxzvXlLUN:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[ipservice/server.go, line 118 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/35#-M66nXKQ7SiNgquNnWqV:-M6Vm2kn-ifbBWCiwl2x:b-34lulg) ([raw file](https://github.com/m-lab/uuid-annotator/blob/1e2a04a37afbc4cbef3a11edd16133d977ed846b/ipservice/server.go#L118)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This new behavior is necessary, if we are to assume that a spurious transient crash in tcp-info or uuid-annotator ever could exist. I understand your comment to be worrying that this new behavior is might not be sufficient.

No clients can be listening on the stale socket, as the server closing causes them to be disconnected. I don't know why Linux doesn't automatically reap socket filenames when the server-side closes, but if the OS won't reap the name,  then we should do what it turns out every other unix-domain-socket service does, and unlink the file right before we bind it. bind of a unix domain socket fails if the filename exists, even if the filename is owned by the current user. unix domain sockets, it turns out, can't be re-used. bind() must be given a filename that does not exist.

Client connections close as soon as the server-side closes, and new connections don't return success unless there is a server listening on the other end.  Crashing (due to a bug or an assertion failure on startup)  and then unlink&bind when the new instance starts is a safe behavior. I can add unit tests of these assertions about the surrounding OS if you would like.
</blockquote></details>

I was definitely thinking of named pipes which can cause readers to block without a writer and are not the same as UDS.

If this is how every other UDS server does it, then that sgtm.

**Comment by pboothe** [comment]
Using admin powers to push despite the failed job, because the "failed job" was just an RPC error to the coveralls.io service.

**Pull request merged**
