### PR TITLE
Fix routeview prefix search

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change corrects the search algorithm used by the uuid-annotator's routeview IP prefix to AS index to reliably find the longest prefix match. The routeview IP prefix to AS dataset provides network annotations for M-Lab's measurement platform.

Previously, the implementation erroneously sorted all network prefixes together and used a binary search to identify a prefix that contained a given IP. Unfortunately, this is incorrect. Network prefixes in the dataset are not mutually exclusive nor the same size. In particular, short prefixes (e.g. 12.0.0.0/9) may contain many (partial) longer prefixes (e.g. 12.189.156.0/24) and be associated with different ASNs. As a result, some searches never find the correct prefix, either because the search lands among longer prefixes that do not contain the given IP (~10% of the time), or (possibly) because an IP is misattributed to a shorter prefix when a longer prefix would have been a better match (unknown %).

Now, network prefixes are grouped into sets of the same block size. Network blocks of the same size cannot overlap. The search checks the index from longest to the shortest block (e.g. 32 to 8), searching for a network prefix of that block size that contains the given IP. If one is found, the search stops. Otherwise the search continues with the next shortest block size. This guarantees that the longest prefix will be found before shorter prefixes. And, if no prefix is found over the complete index, then we know that all possible networks were searched.

Resolves
* https://github.com/m-lab/uuid-annotator/issues/48

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/49)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
It would be nice to add some metrics (number of malformed input files and number of AS not found errors).

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-:-NNbHLY41wE-S1L4eVOR:bllmwt2)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`routeview/parse.go` line 96 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbGVRm2MoeMWn-ru5U:-NNbGVRm2MoeMWn-ru5V:bxyp342) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse.go#L96)):*
> ```Go
> 			// Skip malformed line.
> 			skip++
> 			log.Println("failed to convert netblock size:", record[1])
> ```

Should this be error logged?
___
*[`routeview/parse_test.go` line 188 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbJcDs1W2Iw-L6UYuM:-NNbJMiF9awUGlkgsoah:b-ta5xxg) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse_test.go#L188)):*
> ```Go
> }
> 
> func BenchmarkSearch(b *testing.B) {
> ```

IIUC, this benchmarking shows that the algorithm's performance is going from 715.3 ns/op (in main) to 10188 ns/op (in this branch). Is that a concern?

**Review by stephen-soltesz — COMMENTED** [review]
Metrics are a great idea. I've added counts to the parser and to the ASN annotator's searches.

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-:-NNbSVNt9Y5qkYOEi3W4:b-xtf2cg)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`routeview/parse.go` line 96 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbGVRm2MoeMWn-ru5U:-NNbSJ0dBJd98f9J0IT9:b-46u99s) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse.go#L96)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this be error logged?
</blockquote></details>

Can you say more? What do you have in mind? (The log package writes to stderr by default. Do we have (or should have) a different convention?)
___
*[`routeview/parse_test.go` line 188 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbJcDs1W2Iw-L6UYuM:-NNbUPQyA4GgN3LqvIYK:b-x867rq) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse_test.go#L188)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

IIUC, this benchmarking shows that the algorithm's performance is going from 715.3 ns/op (in main) to 10188 ns/op (in this branch). Is that a concern?
</blockquote></details>

Good question; I saw something similar. My thinking is that the first priority is correcting the lookup. And, each uuid-annotator needs to process at most a few 100k queries / day. The lower benchmark may not have been representative since the previous search method was incorrect. I am more worried about the added RAM pressure the update will create on nodes than the CPU load.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-:-NNcEv-l8VguK-RmjJuW:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`routeview/parse.go` line 96 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbGVRm2MoeMWn-ru5U:-NNcBX25BKQriODkS2Y2:b-z78x4q) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse.go#L96)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can you say more? What do you have in mind? (The log package writes to stderr by default. Do we have (or should have) a different convention?)
</blockquote></details>

If these are being written to stderr, then that seems correct to me.

My concern was that we have some projects where everything is written to the error log (e.g., gardener) and others where everything is written to the info log :upside_down_face:.
___
*[`routeview/parse_test.go` line 188 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbJcDs1W2Iw-L6UYuM:-NNcDT350kQAdk_jWzDF:b-wmyf4a) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse_test.go#L188)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Good question; I saw something similar. My thinking is that the first priority is correcting the lookup. And, each uuid-annotator needs to process at most a few 100k queries / day. The lower benchmark may not have been representative since the previous search method was incorrect. I am more worried about the added RAM pressure the update will create on nodes than the CPU load.
</blockquote></details>

I think it might be helpful to have some sense of how long the queries are taking IRL (e.g., with metrics). If necessary, we can consider [optimizations](https://github.com/m-lab/uuid-annotator/issues/48#issuecomment-1416564278).

I agree fixing the algorithm is the priority, so I don't think it should block this change.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-:-NNcNxSpCSdPqwx8r1ci:b-9755fn)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`routeview/parse.go` line 96 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbGVRm2MoeMWn-ru5U:-NNcN4ImAI4tXMrVpsoL:b-4gkbt6) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse.go#L96)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

If these are being written to stderr, then that seems correct to me.

My concern was that we have some projects where everything is written to the error log (e.g., gardener) and others where everything is written to the info log :upside_down_face:.
</blockquote></details>

Got it. Right, I'm aware of the general problem.

I've proposed that we add `Info` and `Error` loggers to the logx package https://pkg.go.dev/github.com/m-lab/go@v0.1.56/logx so we could differentiate between these cases in code and even optionally enable or disable them. It will take time to migrate things but starting with some convention would be the first step. I'm open to alternative proposals too of course.
___
*[`routeview/parse_test.go` line 188 at r1](https://reviewable.io/reviews/m-lab/uuid-annotator/49#-NNbJcDs1W2Iw-L6UYuM:-NNcNtCv0T2cKxa6bOyi:b-8fptl4) ([raw file](https://github.com/m-lab/uuid-annotator/blob/372185fde552728a8157c35490b5e31d230bb86b/routeview/parse_test.go#L188)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I think it might be helpful to have some sense of how long the queries are taking IRL (e.g., with metrics). If necessary, we can consider [optimizations](https://github.com/m-lab/uuid-annotator/issues/48#issuecomment-1416564278).

I agree fixing the algorithm is the priority, so I don't think it should block this change.
</blockquote></details>

sgtm :+1:

**Pull request merged**
